[package]
name = "zingerboost"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
tauri-plugin-shell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

zb_app = { path = "../crates/zb_app" }
zb_domain = { path = "../crates/zb_domain" }
zb_application = { path = "../crates/zb_application" }
zb_infrastructure = { path = "../crates/zb_infrastructure" }
